#!/bin/bash

ksv_xdg_dirs=/usr/share
ksv_xdg_dir=
ksv_def_icon_theme=icons/hicolor

function ks_init()
{
	set -e
	for i in `echo "${ksv_xdg_dirs}" | sed 's/:/ /g'`
	do
		if [ -w ${i}/${ksv_def_icon_theme} ] ; then
			ksv_xdg_dir="${i}"
		fi
	done
}

function ks_remove()
{
	if [ -e /etc/xdg/menus/applications-merged/wps-office.menu ] ; then
		rm -rf /etc/xdg/menus/applications-merged/wps-office.menu
	fi

	if [ -x /usr/bin/update-mime-database ] ; then
		update-mime-database "${ksv_xdg_dir}/mime"
	fi

	if [ -x /usr/bin/update-desktop-database ] ; then
		update-desktop-database -q "${ksv_xdg_dir}/applications"
	fi

	rm -rf /usr/share/applications/wps-office-wps.desktop
	rm -rf /usr/share/applications/wps-office-wpp.desktop
	rm -rf /usr/share/applications/wps-office-et.desktop
	rm -rf /usr/share/applications/wps-office-misc.desktop
	
	if [ -f "/usr/share/applications/wps-office-misc.desktop" ]; then
		rm -rf /usr/share/applications/wps-office-misc.desktop
	fi

	for HOMEDIR in /home/*; do
		OA_CONF_PATH="$HOMEDIR/.kingsoft/wps/jsaddons"
		if [ -d "$OA_CONF_PATH" ]; then
			rm -rf "$OA_CONF_PATH"
		fi
		# 卸载WPS时删除邮箱账号信息
		if [ -f "$HOMEDIR/.local/share/Kingsoft/office6/mailconfig/encrypt.txt" ]; then
			rm -rf "$HOMEDIR/.local/share/Kingsoft/office6/mailconfig/encrypt.txt"
		fi
		if [ -f "$HOMEDIR/.kingsoft/office6/mailconfig/encrypt.txt" ]; then
			rm -rf "$HOMEDIR/.kingsoft/office6/mailconfig/encrypt.txt"
		fi
		# 卸载WPS时删除云文档登录信息
		if [ -d "$HOMEDIR/.local/share/Kingsoft/account" ]; then
			rm -rf "$HOMEDIR/.local/share/Kingsoft/account"
		fi 
		# 卸载WPS时删除文件搜索缓存数据
		if [ -d "$HOMEDIR/.local/share/Kingsoft/Ksearch" ]; then
			rm -rf "$HOMEDIR/.local/share/Kingsoft/Ksearch"
		fi
		# 卸载删除关联检测文件
		if [ -f "$HOMEDIR/.local/share/mime/packages/Override.xml" ]; then
			rm -rf "$HOMEDIR/.local/share/mime/packages/Override.xml"
			if [ -x /usr/bin/update-mime-database ]; then
				update-mime-database "$HOMEDIR/.local/share/mime" >/dev/null 2>&1 || true
			fi
		fi
	done
	rm -rf /usr/share/applications/appurl.desktop

	if [ -f '/usr/bin/caja' ] && [ -f '/usr/bin/xdotool' ]; then
		{ xdotool search --class caja key F5; } 2>/dev/null || true # 向caja桌面系统发送F5 解决中标系统安装后不刷新的问题
	fi 
}

function ks_main()
{
	if [ $# -eq 0 ] ; then
		return;
	fi

	ks_init
	case $1 in
		remove )
			shift
			ks_remove $@
			;;
		purge )
			;;
		abort-install )
			;;
		abort-upgrade )
			;;
		failed-upgrade )
			;;
	esac
}

ks_main $@


